(() => {
'use strict';
const {rooms,initial,check,finalAssessment,scoreAssessment}=EscapeCore;
const STORAGE='device-escape-v1';
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({version:1,started:false,finished:false,room:0,steps:[0,0,0,0,0,0],passed:[false,false,false,false,false,false],controls:rooms.map(initial),attempts:[],answers:[],discoveries:[],hints:[0,0,0,0,0,0],predictions:['','','','','',''],pending:[false,false,false,false,false,false],name:'',reflection:'',assessment:{answers:{},submitted:false},challenge:null,elapsed:0,reduced:false,sound:false});
let state=fresh(),storageOK=true,feedback=null,pending=false,busy=false,toastTimer,audioContext;
try{const data=JSON.parse(localStorage.getItem(STORAGE)||'null');if(data&&data.version===1&&Array.isArray(data.steps)&&data.steps.length===6&&data.steps.every(n=>Number.isInteger(n)&&n>=0&&n<=3)&&Array.isArray(data.passed)&&data.passed.length===6&&data.passed.every(n=>typeof n==='boolean')&&Array.isArray(data.controls)&&data.controls.length===6&&data.controls.every(c=>c&&typeof c==='object')&&Number.isInteger(data.room)&&data.room>=0&&data.room<6&&['attempts','answers','discoveries','hints','predictions'].every(k=>Array.isArray(data[k]))){state={...fresh(),...data};state.controls=state.controls.map(c=>({...initial(),...c}));}}catch(e){storageOK=false;}
pending=!!state.pending?.[state.room];
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));}catch(e){if(storageOK){storageOK=false;toast('浏览器无法保存进度。请在离开前导出线索簿。');}}}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4800);}
function sound(){if(!state.sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.setValueAtTime(660,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(880,audioContext.currentTime+.15);g.gain.setValueAtTime(.035,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.4);o.start();o.stop(audioContext.currentTime+.4);}catch(e){toast('声音不可用；所有线索都有文字与画面提示。');}}
const minutes=()=>Math.floor(state.elapsed/60);
function top(){return `<header class="topbar"><div class="brand"><span class="brand-logo">◈</span><span>机关密室<small>THE CONTROL CHAMBERS</small></span></div><nav class="toolbar" aria-label="工具"><button class="plain" data-action="notebook">线索簿</button><button class="plain mobile-hide" data-action="sound" aria-pressed="${state.sound}">声音${state.sound?'开':'关'}</button><button class="plain optional" data-action="motion" aria-pressed="${state.reduced}">${state.reduced?'恢复动画':'减少动态'}</button></nav></header>`;}
function footer(){return `<footer class="footer"><span>六年级信息科技 · 第1课 设备控制处处在</span><span>${storageOK?'进度保存在当前浏览器':'进度保存不可用，请及时导出'} · 无需登录</span></footer>`;}
function render(focusKey){document.body.classList.toggle('reduced',state.reduced);$('#app').innerHTML=`<div class="wrap">${top()}${!storageOK?'<div class="save-warning">当前浏览器不能保存进度。请使用线索簿导出记录，刷新可能丢失进度。</div>':''}${!state.started?landing():state.finished?finish():game()}${footer()}</div>`;if(focusKey){const el=document.querySelector(`[data-focus="${focusKey}"]`);el?.focus({preventScroll:true});}}
function landing(){return `<section class="landing"><div class="hero-copy"><span class="pill"><i class="dot"></i> 一场靠观察与操作完成的冒险</span><h1>机关密室<em>设备控制逃脱行动</em></h1><p>五枚晶石，六道机关。<br>和探险搭档一起，唤醒沉睡的设备。<br>每一次控制，都藏着打开出口的线索。</p><button class="primary" data-action="start">进入密室 <span aria-hidden="true">→</span></button><div class="hero-meta"><span>◷ 约25—30分钟</span><span>⌘ 点击操作</span><span>♧ 支持双人合作</span></div><p style="font-size:12px;margin:20px 0 0">没有倒计时惩罚。可以尝试，也可以求助。<br>建议一人操作、一人观察，每间密室交换角色。</p></div><div class="cover-caption"><b>阿澄 × 小屿 × 机械向导</b>找到设备 · 观察变化 · 收集线索</div></section><div class="journey">${rooms.map((r,i)=>`<div class="preview"><div class="thumb" style="background-position:${(i%3)*50}% ${i<3?0:100}%"></div><div><b>${String(i+1).padStart(2,'0')} ${r.name.replace('终局 · ','')}</b><small>${i===5?'运用线索，打开出口':r.key+' · 等待发现'}</small></div></div>`).join('')}</div>`;}
function game(){const r=rooms[state.room],s=state.steps[state.room],count=state.passed.filter(Boolean).length;return `<div class="game-heading"><div><div class="eyebrow">CHAMBER ${String(state.room+1).padStart(2,'0')} / 06 · ${r.tag}</div><h1>${r.name}</h1></div><div class="progress-overview"><span class="muted">已取证 ${count} / 6 间</span><div class="progress-line"><span style="width:${count/6*100}%"></span></div></div></div><div class="game-layout"><nav class="room-nav" aria-label="密室路线">${rooms.map((x,i)=>`<button class="room-btn ${i===state.room?'active':''} ${state.passed[i]?'done':''}" data-action="room" data-room="${i}" ${i>0&&!state.passed[i-1]?'disabled':''} ${i===state.room?'aria-current="step"':''} aria-label="第${i+1}间 ${x.name}${i>0&&!state.passed[i-1]?' 未解锁':''}"><span class="nav-icon">${x.icon}</span>${['光影','风力','模式','城市','时间','出口'][i]}</button>`).join('')}</nav><div class="stage-col">${scene()}<div class="guide"><span class="avatar" aria-hidden="true"></span><div><b>机械向导 · 小序</b><p>${s===0&&!pending?r.intro:state.passed[state.room]?'这里的控制线索已经记录好了。你可以继续探索，或者前往下一间。':s===3?'机关响应正确！再解释一次你的发现，就能取得晶石。':'观察设备的反应：它实现了你需要的功能吗？想好后，再启动试运行。'}</p></div></div></div><aside class="task-panel" aria-label="当前任务与控制面板">${state.passed[state.room]?collected():s>=3?question():taskPanel()}</aside></div><div class="clue-tray"><div><div class="eyebrow">YOUR EVIDENCE</div><b>控制线索 · 晶石槽</b></div><div class="clue-slots">${rooms.slice(0,5).map((x,i)=>`<span class="crystal ${state.passed[i]?'collected':''}" title="${state.passed[i]?x.key:'尚未获得'+x.key}" aria-label="${state.passed[i]?'已获得':'未获得'}${x.key}">${state.passed[i]?x.icon:'·'}</span>`).join('')}</div><button class="plain" data-action="notebook">查看线索簿 ↗</button></div>`;}
const switcher=(key,label)=>`<div class="toggle-row"><span>${label}</span><button class="switch" role="switch" aria-label="${label}" aria-checked="${!!state.controls[state.room][key]}" data-action="toggle" data-key="${key}" data-focus="${key}"></button></div>`;
function choices(key,label,values){return `<div class="control-group"><span class="control-label">${label}</span><div class="choices">${values.map(v=>{const [value,text]=Array.isArray(v)?v:[v,String(v)];return `<button type="button" data-action="set" data-key="${key}" data-value="${esc(value)}" data-number="${typeof value==='number'}" data-focus="${key}-${esc(value)}" class="${state.controls[state.room][key]===value?'selected':''}" aria-pressed="${state.controls[state.room][key]===value}">${esc(text)}</button>`;}).join('')}</div></div>`;}
function controls(){const r=state.room,s=state.steps[r];
 if(r===0||(r===5&&s!==1))return `${s===2?switcher('audio','音频播放器')+choices('volume','音量 / 格',[0,1,2,3]):switcher('lamp','照明灯')+(r===0&&s===0?'':switcher('projector','投影设备')+switcher('curtain','合上窗帘'))}`;
 if(r===1||r===5)return `${switcher('fan','风扇电源')}<div style="height:12px"></div>${choices('speed','风速 / 挡',[[0,'停风'],[1,'1 · 轻风'],[2,'2 · 中风'],[3,'3 · 强风']])}${choices('timer','定时停止 / 分钟',[[0,'不定时'],15,30,60])}<p class="note">试运行会快进定时过程。风扇促进空气流动。</p>`;
 if(r===2)return s<2?`${switcher('washer','洗衣机电源')}<div style="height:12px"></div>${choices('wmode','洗衣机模式',['快洗','脱水','标准'])}<p class="note">课堂模拟面板；不同型号的实际操作可能不同。</p>`:`${switcher('cooker','电饭锅电源')}<div style="height:12px"></div>${choices('cmode','电饭锅模式',['煮饭','煮粥','保温'])}<p class="note">只进行屏幕模拟，不操作真实加热设备。</p>`;
 if(r===3)return `${choices('role','谁在控制设备？',['驾驶员','交通管理部门','城市管理部门'])}${s===0?switcher('vehicle','启动模拟车辆'):s===1?choices('signal','模拟信号状态',['全部停止','东西通行','南北通行']):switcher('street','路灯')}<p class="note">本舱仅模拟公共设备；真实设备由相应人员管理。</p>`;
 if(r===4){const c=state.controls[r];if(s===0)return `${choices('key','锁孔提示：匹配齿形钥匙',['圆头钥匙','齿形钥匙','方头钥匙'])}<button data-action="old-lock" data-focus="old-lock" class="run">转动钥匙</button><p class="note">锁的状态：${c.oldOpen?'已经打开':'尚未打开'}</p>`;
 if(s===1)return `<p class="note">密码线索：按获得顺序，组合<b>前三枚晶石上的数字</b>。打开顶部“线索簿”查看。</p><div class="code-display" aria-label="已输入密码">${esc(c.code||'— — —')}</div><div class="keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-action="digit" data-focus="digit-${n}" data-digit="${n}" aria-label="密码数字${n}">${n}</button>`).join('')}</div><div class="digit-action"><button data-action="clear-code" data-focus="clear-code">清除</button><button data-action="smart-lock" data-focus="smart-lock">验证开锁</button></div><p class="note">锁的状态：${c.smartOpen?'已经打开':'尚未打开'}</p>`;
 return choices('evolution','选择发展档案中的结论',['所有功能都改变了','控制方法改变，开门功能保留','两种锁的控制方法完全相同']);}
 return '';}
function taskPanel(){const r=rooms[state.room],s=state.steps[state.room],t=r.tasks[s];return `<div class="task-head"><div class="eyebrow">机关任务 ${s+1} / 3</div><h2>${t.title}</h2><p>${t.goal}</p><div class="step-track">${[0,1,2].map(i=>`<i class="${i<s?'done':i===s?'current':''}"></i>`).join('')}</div></div><div class="panel-body"><fieldset class="control-set" ${busy||pending?'disabled':''}>${controls()}<div class="prediction"><label class="control-label" for="prediction">试运行前，预测会发生什么</label><select id="prediction"><option value="">选择你的预测…</option>${[t.expect,'设备没有实现任务需要的变化','还不确定，先试验再比较'].map(x=>`<option value="${esc(x)}" ${state.predictions[state.room]===x?'selected':''}>${x}</option>`).join('')}</select></div></fieldset>${feedbackHTML()}${pending?'<button class="primary run" data-action="next-step">记录发现，继续 →</button>':`<button class="primary run" data-action="run" ${busy?'disabled':''}>${busy?'正在试运行…':'▷ 启动试运行'}</button>`}<button class="hint-btn" data-action="hint" data-focus="hint" ${busy?'disabled':''}>✧ ${state.hints[state.room]?'再给我一点提示':'需要一点提示'} (${Math.min(state.hints[state.room],3)}/3)</button>${state.hints[state.room]?`<div class="hint-box">${r.hints[Math.min(state.hints[state.room]-1,2)]}</div>`:''}</div>`;}
function feedbackHTML(){return feedback?`<div class="feedback ${feedback.ok?'success':''}" role="status"><strong>${feedback.ok?'✓ 机关回应了':'观察结果'}</strong>${esc(feedback.text)}</div>`:'';}
function question(){const q=rooms[state.room].question;return `<div class="question"><div class="eyebrow">线索取证 · 解释你的发现</div><h3>${q.title}</h3><p class="muted" style="font-size:12px">把操作与原因连起来，晶石才会点亮。</p>${q.options.map((x,i)=>`<button class="answer" data-action="answer" data-focus="answer-${i}" data-answer="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}${feedbackHTML()}</div>`;}
function collected(){const r=rooms[state.room];return `<div class="complete-panel"><div class="eyebrow">EVIDENCE COLLECTED</div><div class="key-display">${r.icon}</div><h2>${state.room===5?'出口已开启！':'获得'+r.key}</h2><p>${r.question.explain}</p>${state.room<3?`<div class="feedback success">晶石背面刻着 <b>${[2,4,6][state.room]}</b>。已收进线索簿，时间锁会用到。</div>`:""}<button class="primary run" data-action="next-room" data-focus="next-room">${state.room===5?'查看我的闯关成果':'前往下一间密室 →'}</button><button class="plain run" data-action="notebook">查看本次操作记录</button></div>`;}
function svg(body,w=240,h=240){return `<svg viewBox="0 0 ${w} ${h}" aria-hidden="true"><defs><linearGradient id="metal" x2="1" y2="1"><stop stop-color="#f9eac0"/><stop offset=".46" stop-color="#bc9356"/><stop offset="1" stop-color="#795837"/></linearGradient><linearGradient id="case" x2="1" y2="1"><stop stop-color="#627f7b"/><stop offset=".48" stop-color="#2c5355"/><stop offset="1" stop-color="#162e3a"/></linearGradient><linearGradient id="glass" x2="0" y2="1"><stop stop-color="#113841"/><stop offset="1" stop-color="#346a6e"/></linearGradient></defs>${body}</svg>`;}
function fan(c){return `<div class="device">${svg(`<ellipse cx="120" cy="222" rx="63" ry="11" fill="#102d35"/><path d="M100 155h40v53h-40z" fill="url(#case)" stroke="#bda876" stroke-width="3"/><path d="M78 209Q120 192 162 209l7 14H71z" fill="url(#metal)"/><circle cx="120" cy="95" r="82" fill="url(#case)" stroke="url(#metal)" stroke-width="8"/><g class="${c.fan&&c.speed?'spinner':''}" style="--spin:${[0,2,1,.45][c.speed]||2}s"><path d="M120 95C66 14 169 2 141 77C214 38 230 128 151 112C193 183 100 199 106 121C30 155 16 64 98 82Z" fill="url(#metal)" stroke="#eed6a5" stroke-width="2"/></g>${[30,48,65,77].map(n=>`<circle cx="120" cy="95" r="${n}" fill="none" stroke="#ddcc9c" stroke-width="1" opacity=".7"/>`).join('')}<path d="M38 95h164M120 13v164M62 37l116 116M62 153L178 37" stroke="#d4c599" opacity=".8"/><circle cx="120" cy="95" r="14" fill="url(#metal)"/><circle cx="120" cy="95" r="5" fill="${c.fan?'#afffdd':'#455c60'}"/>`)}<span class="device-label">电风扇 · ${c.fan?c.speed+'挡运行':'已关闭'}</span></div>`;}
function lamp(c){return `<div class="device">${svg(`${c.lamp?'<ellipse cx="120" cy="210" rx="100" ry="18" fill="#fff4b6" opacity=".5"/><path d="M87 95L15 220h210L153 95Z" fill="#ffe69f" opacity=".24"/>':''}<path d="M116 87h10v123h-10z" fill="url(#metal)"/><ellipse cx="120" cy="215" rx="55" ry="12" fill="url(#case)" stroke="#b59960" stroke-width="3"/><path d="M76 60Q120 15 164 60l22 50H54Z" fill="url(#case)" stroke="url(#metal)" stroke-width="4"/><ellipse cx="120" cy="109" rx="64" ry="13" fill="${c.lamp?'#ffebb0':'#6b755f'}" stroke="#b59b62" stroke-width="3"/><circle cx="120" cy="107" r="12" fill="${c.lamp?'#fffde2':'#999c84'}"/>`)}<span class="device-label">照明灯 · ${c.lamp?'亮':'灭'}</span></div>`;}
function projector(c){return `<div class="device">${svg(`${c.projector?'<path d="M145 109L238 35V174Z" fill="#f6e4ac" opacity=".2"/>':''}<path d="M45 185l-5 22M161 185l5 22" stroke="#b49b6b" stroke-width="8"/><rect x="25" y="95" width="170" height="94" rx="17" fill="url(#case)" stroke="url(#metal)" stroke-width="4"/><rect x="40" y="112" width="52" height="38" rx="5" fill="#192e34"/>${[0,1,2,3].map(i=>`<path d="M46 ${120+i*7}h38" stroke="#829d91"/>`).join('')}<circle cx="154" cy="136" r="30" fill="#17353d" stroke="#ccac74" stroke-width="6"/><circle cx="154" cy="136" r="20" fill="${c.projector?'#e8fff5':'#456874'}"/><circle cx="60" cy="166" r="4" fill="${c.projector?'#93eab7':'#526960'}"/>`)}<span class="device-label">投影设备 · ${c.projector?'已启动':'待机'}</span></div>`;}
function speaker(c){return `<div class="device">${svg(`<rect x="57" y="32" width="126" height="188" rx="18" fill="url(#case)" stroke="url(#metal)" stroke-width="5"/><circle cx="120" cy="88" r="29" fill="#142f39" stroke="#b9a172" stroke-width="4"/><circle cx="120" cy="88" r="12" fill="#667f78"/><circle cx="120" cy="162" r="42" fill="#18343e" stroke="#b6a175" stroke-width="4"/><circle cx="120" cy="162" r="23" fill="url(#case)" stroke="#597b7a" stroke-width="3"/>${c.audio&&c.volume?[0,1,2].map((i)=>`<path d="M${199+i*10} ${95-i*12}q${16+i*5} ${15+i*12} 0 ${30+i*24}" stroke="#b6e8d6" stroke-width="3" fill="none" class="pulse" style="animation-delay:${i*.2}s"/>`).join(''):''}<circle cx="120" cy="45" r="3" fill="${c.audio?'#a2f7cf':'#60776f'}"/>`)}<span class="device-label">播放器 · ${c.audio?'音量'+c.volume+'格':'未播放'}</span></div>`;}
function washer(c){return `<div class="device">${svg(`<rect x="39" y="20" width="162" height="207" rx="16" fill="url(#case)" stroke="url(#metal)" stroke-width="4"/><rect x="52" y="34" width="136" height="40" rx="6" fill="#102e35"/><circle cx="74" cy="54" r="12" fill="url(#metal)"/><text x="97" y="59" font-size="13" fill="#bcf0d5">${c.washer?c.wmode:'未启动'}</text><circle cx="120" cy="141" r="59" fill="#bda475"/><circle cx="120" cy="141" r="50" fill="url(#glass)" stroke="#233c40" stroke-width="6"/><g class="${c.washer&&c.wmode!=='未选择'?'spinner':''}" style="--spin:${c.wmode==='脱水'?'.6':'2'}s"><path d="M83 127q38-40 70 11q-26 48-63 35z" fill="#c2d4bf" opacity=".85"/><path d="M118 99l35 34-22 18-39-22z" fill="#d9b682"/></g><path d="M78 110q-14 45 12 69" stroke="#deefe1" stroke-width="3" opacity=".5" fill="none"/><circle cx="184" cy="136" r="6" fill="url(#metal)"/>`)}<span class="device-label">洗衣机 · ${c.washer?c.wmode:'已关闭'}</span></div>`;}
function cooker(c){return `<div class="device">${svg(`${c.cooker?'<g class="steam" stroke="#fff4dd" fill="none" stroke-width="4" opacity=".6"><path d="M100 60q-10-20 0-35M122 60q-10-20 0-35M144 60q-10-20 0-35"/></g>':''}<path d="M59 100Q40 235 120 229q80 6 61-129z" fill="url(#case)" stroke="url(#metal)" stroke-width="4"/><ellipse cx="120" cy="100" rx="70" ry="24" fill="url(#metal)"/><ellipse cx="120" cy="94" rx="59" ry="18" fill="url(#case)"/><path d="M100 82V65q20-17 40 0v17" fill="none" stroke="#dbc291" stroke-width="9"/><rect x="83" y="151" width="75" height="37" rx="7" fill="#102e35" stroke="#668b7f"/><text x="120" y="175" text-anchor="middle" fill="#b8f3d6" font-size="14">${c.cooker?c.cmode:'未启动'}</text><path d="M55 129H36v26h18M185 129h19v26h-19" stroke="#b39966" stroke-width="6" fill="none"/>`)}<span class="device-label">电饭锅 · ${c.cooker?c.cmode:'已关闭'}</span></div>`;}
function city(c){return `<div class="device" style="width:100%">${svg(`<rect x="10" y="25" width="460" height="190" rx="20" fill="#15353c" stroke="url(#metal)" stroke-width="3"/><rect x="190" y="30" width="100" height="180" fill="#586b68"/><path d="M15 90h450v65H15Z" fill="#586b68"/><path d="M235 35v160M20 123h435" stroke="#d6d2ad" stroke-width="2" stroke-dasharray="13 9"/>${[0,1,2,3].map(i=>`<path d="M${172+i*7} 94v56M${296+i*7} 94v56" stroke="#e4e3ca" stroke-width="4"/>`).join('')}<g class="${(state.steps[state.room]===0?c.vehicle:c.signal==='东西通行')?'moving-car':''}"><rect x="40" y="111" width="60" height="25" rx="8" fill="#e8c785"/><rect x="57" y="114" width="22" height="19" rx="3" fill="#244651"/></g><rect x="309" y="45" width="29" height="52" rx="7" fill="#17282b" stroke="#baa279"/><circle cx="323" cy="59" r="7" fill="${c.signal==='东西通行'?'#494c3e':'#fb9378'}"/><circle cx="323" cy="81" r="7" fill="${c.signal==='东西通行'?'#a7ebbd':'#404d45'}"/><path d="M324 97v27" stroke="#a28b65" stroke-width="5"/><path d="M384 66v123M375 69q9-25 18 0Z" stroke="#ac925b" fill="${c.street?'#ffe6a2':'#5c756a'}" stroke-width="4"/>${c.street?'<ellipse cx="384" cy="183" rx="46" ry="13" fill="#ffe4a8" opacity=".5"/>':''}<text x="33" y="193" fill="#c7e2d8" font-size="14">${esc(c.role==='未选择'?'选择控制者，再操作设备':c.role)}</text>`,480,240)}<span class="device-label">街道模拟台 · ${c.signal}</span></div>`;}
function locks(c){return `<div class="device" style="width:100%">${svg(`<rect x="18" y="47" width="146" height="166" rx="15" fill="url(#case)" stroke="url(#metal)" stroke-width="5"/><path d="M60 70V43a32 32 0 0 1 64 0v${c.oldOpen?0:27}" fill="none" stroke="url(#metal)" stroke-width="13" transform="${c.oldOpen?'translate(0,-14)':''}"/><circle cx="92" cy="129" r="29" fill="url(#metal)"/><path d="M85 120h14v29H85z" fill="#21404a"/><text x="91" y="187" text-anchor="middle" fill="#e5d2a1" font-size="14">${c.oldOpen?'机械锁已打开':'机械钥匙门锁'}</text><rect x="216" y="34" width="136" height="180" rx="18" fill="url(#case)" stroke="url(#metal)" stroke-width="4"/><rect x="232" y="50" width="104" height="47" rx="6" fill="#173039"/><text x="284" y="80" text-anchor="middle" fill="#b4f8d8" font-size="20">${c.smartOpen?'已开锁':esc(c.code||'···')}</text>${[0,1,2,3,4,5,6,7,8].map((n)=>`<circle cx="${253+n%3*30}" cy="${117+Math.floor(n/3)*24}" r="5" fill="${c.smartOpen?'#9ce8c3':'#c7b485'}"/>`).join('')}<path d="M251 193h67" stroke="#ceb77e" stroke-width="8" stroke-linecap="round"/>`,375,240)}<span class="device-label">控制方式改变 · 基本功能延续</span></div>`;}
function windMechanism(c){const s=state.steps[state.room],final=state.room===5;let body,label;
if(final){body=`<path d="M25 155h175" stroke="#b6a177" stroke-width="8"/><g class="${c.fan&&c.speed===2?'key-travel':''}" transform="translate(45,85)"><path d="M0 0h37v18H20v16H0z" fill="#e8c580" stroke="#fff0b4" stroke-width="3"/></g>`;label=c.fan?'模拟钥匙传送':'机关待启动';}
else if(s===0){body=`<circle cx="115" cy="105" r="67" fill="#123c43" stroke="#bba275" stroke-width="8"/><g class="${c.fan&&c.speed?'spinner':''}" style="--spin:${c.speed===3?'.8':'4'}s">${[0,45,90,135].map(a=>`<path d="M63 105h104" stroke="#ead3a1" stroke-width="13" transform="rotate(${a} 115 105)"/>`).join('')}</g><circle cx="115" cy="105" r="19" fill="#d3b373"/>`;label=c.fan&&c.speed===3?'叶轮达到机关要求':'重型叶轮 · 需要强风';}
else if(s===1){body=`<path d="M15 180h195" stroke="#b6a177" stroke-width="6"/><g class="${c.fan&&c.speed===1?'feather-float':c.fan&&c.speed>1?'feather-away':''}"><path d="M65 160Q31 52 139 42Q177 133 65 160Z" fill="#e0edce" stroke="#ffe9b5" stroke-width="3"/><path d="M61 179L140 39M82 145l-30-25M96 116l-34-24M108 95l34 0M93 129l35 0" stroke="#96b59b" stroke-width="3" fill="none"/></g>`;label=c.fan&&c.speed===1?'羽片被轻风平稳托起':c.fan&&c.speed>1?'气流过强，羽片偏离':'轻羽片 · 等待气流';}
else{body=`<circle cx="115" cy="108" r="70" fill="#e9d7ad" stroke="#b19159" stroke-width="7"/><circle cx="115" cy="108" r="60" fill="#1a3940"/><g class="${busy&&c.fan?'spinner':''}" style="--spin:.6s"><path d="M115 62v46h37" stroke="#d5e8cd" fill="none" stroke-width="5" stroke-linecap="round"/></g><text x="115" y="150" fill="#e7d1a3" font-size="14" text-anchor="middle">${c.timer?c.timer+'分钟':'未定时'}</text>`;label=c.fan?'定时控制停止时刻':'到时停止 / 当前已停';}
return `<div class="device mechanism">${svg(body)}<span class="device-label">${label}</span></div>`;}
function scene(){const i=state.room,c=state.controls[i],step=state.steps[i];const chips=[];
 if(i===0||i===5)chips.push(['照明 '+(c.lamp?'亮':'灭'),c.lamp],['投影 '+(c.projector?'开':'关'),c.projector],['窗帘 '+(c.curtain?'合':'开'),c.curtain],['播放 '+(c.audio?'音量'+c.volume:'关'),c.audio]);
 if(i===1||i===5)chips.push(['风速 '+c.speed+'挡',c.fan],['定时 '+(c.timer?c.timer+'分钟':'未设'),!!c.timer]);
 if(i===2)chips.push(['洗衣机 '+(c.washer?c.wmode:'关'),c.washer],['电饭锅 '+(c.cooker?c.cmode:'关'),c.cooker]);
 if(i===3)chips.push([c.role,c.role!=='未选择'],[c.signal,c.signal!=='全部停止'],['路灯 '+(c.street?'亮':'灭'),c.street]);
 if(i===4)chips.push(['机械锁 '+(c.oldOpen?'打开':'关闭'),c.oldOpen],['智能锁 '+(c.smartOpen?'打开':'关闭'),c.smartOpen]);
 let devices=i===1?fan(c)+windMechanism(c):i===2?(step===2?cooker(c):washer(c)):i===3?city(c):i===4?locks(c):i===5&&step===1?fan(c)+windMechanism(c):step===2?speaker(c):i===0&&step===0?lamp(c):projector(c);
 const tips=['观察墙上机关','检查装置标记','寻找隐藏档案'];
 return `<div class="stage"><div class="room-art" style="background-position:${i%3*50}% ${i<3?0:100}%;filter:brightness(${i===0&&!c.lamp&&!c.projector?.52:1})"></div><div class="room-badge"><span>${rooms[i].icon}</span> ${i===5?'出口验证舱':'机关探索区'} <span>·</span> ${state.passed[i]?'已取证':'等待回应'}</div><div class="stage-tip">点击 ✧ 寻找房间里的观察提示</div>${[0,1,2].map(n=>`<button class="hotspot ${state.discoveries.includes(i+'-'+n)?'found':''}" data-action="discover" data-discovery="${n}" aria-label="${tips[n]}">${state.discoveries.includes(i+'-'+n)?'✓':'✧'}</button>`).join('')}${(i===0&&step===1)||(i===5&&step===0)?`<div class="scene-screen ${!c.projector?'off':!c.curtain||c.lamp?'faint':''}" aria-label="${!c.projector?'无投影':!c.curtain||c.lamp?'图案较模糊':'清晰的线索图案'}">◈ ✧ ⬡</div>`:''}<div class="apparatus">${devices}</div><div class="state-row">${chips.map(([s,on])=>`<span class="state-chip ${on?'on':''}">${esc(s)}</span>`).join('')}</div>${pending?`<div class="burst">${rooms[i].icon}</div>`:''}</div>`;}
function openModal(title,html){const d=$('#modal');$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;if(!d.open)d.showModal();}
function tableRecords(){return state.attempts.length?`<div class="scroll-table"><table><thead><tr><th>设备与任务</th><th>我的预测</th><th>控制方法 / 实际设置</th><th>观察结果</th></tr></thead><tbody>${state.attempts.map(a=>`<tr><td>${esc(rooms[a.room]?.tasks[a.step]?.device)}<br>${esc(a.title)}</td><td>${esc(a.prediction)}</td><td>${esc(a.operation)}</td><td>${a.ok?'✓':'↻'} ${esc(a.result)}</td></tr>`).join('')}</tbody></table></div>`:'<p>线索簿还是空的。操作设备并试运行后，你的尝试会记录在这里。</p>';}
function noteBook(){openModal('我的控制线索簿',`<p>这里保留成功与需要调整的尝试。先看设备做了什么，再解释为什么。</p><label for="team-name">小组代号（选填，不需要真实姓名）</label><input id="team-name" maxlength="30" value="${esc(state.name)}" placeholder="例如：星光探险队"><div class="achievement-grid"><div class="achievement"><b>${state.attempts.filter(a=>a.ok).length}</b><span>任务完成</span></div><div class="achievement"><b>${state.passed.filter(Boolean).length}/6</b><span>解释取证</span></div><div class="achievement"><b>${state.attempts.filter(a=>!a.ok).length}</b><span>调整机会</span></div></div>${tableRecords()}<h3>收集到的晶石刻字</h3><p>按获得顺序：${rooms.slice(0,3).map((r,i)=>`${r.key}：${state.passed[i]?[2,4,6][i]:"尚未获得"}`).join(" → ")}。在时间锁中组合使用。</p><h3>我的解释记录</h3>${state.answers.length?state.answers.map(a=>`<div class="record-item"><b>${esc(rooms[a.room].name)} · ${a.ok?'解释正确':'继续思考'}</b><p>${esc(a.answer)}</p></div>`).join(''):'<p>完成一间密室的操作后，会出现解释任务。</p>'}<label for="reflection">迁移到身边：我会怎样控制一种设备，实现什么功能？</label><textarea id="reflection" maxlength="800" placeholder="我想让____实现____。我会先____，再____；我会通过____判断是否成功。">${esc(state.reflection)}</textarea><p class="note">开放表达由教师或同伴评阅，游戏不自动判断文字是否正确。</p><div class="modal-actions"><button class="primary" data-action="export">导出闯关报告</button><button data-action="close">返回探索</button></div>`);}
function teacher(){openModal('教师指南 · 本课怎样使用',`<p><b>六年级《设备控制处处在》</b> · 主线约25—30分钟，建议两人一组、每间交换操作与观察角色。时长为活动设计估计，尚需学生课堂试用。</p><h3>这节课观察三个目标</h3><p>① 能说清常见设备的功能与控制方法；② 知道身边一些设备可以看作控制系统；③ 能用门锁实例说明控制方式的发展及其便利。</p><div class="teaching-note">教材第11—14页；课标“过程与控制”第30—32页、“小型系统模拟”第32—34页，教学与评价建议第48—49页。反馈、输入/计算/输出与逻辑运算是后续学习内容，本课不作必过关要求。</div><h3>40分钟课堂建议</h3><p>导入3分钟 → 示范2分钟 → 闯关25分钟 → 自创机关、同伴验证5分钟 → 展示与迁移检测5分钟。学生用时较长时，把自创机关放到下一课前或课后。</p><h3>何时介入</h3><p>第1间后追问“你控制什么、怎样控制、发生什么变化”；第3间后比较“开机”和“选模式”；第4间后引出控制系统；第5间后讨论技术进步与适用条件。</p><h3>如何评价</h3><p>线索簿记录预测、实际设置、试验结果与解释尝试。通关是证据之一，结合学生的迁移表达和同伴机关评价。不得用速度、提示次数或画面精美程度替代学习评价。</p><h3>启动与数据</h3><p>可直接打开 index.html，也可使用“启动局域网”文件。学生与教师电脑连接同一网络后访问教师电脑显示的地址。每台学生设备的进度保存在自己的浏览器，教师端不集中收集；学生需要导出报告后通过学校已有渠道提交。</p><h3>显示与声音</h3><p>默认静音；线索不依赖声音。工具栏可减少动态效果。模拟面板不代表所有品牌的真实设备；城市舱仅为模拟，不指导学生操作公共设备。</p><details><summary>查看教师用通关要点</summary>${rooms.map((r,i)=>`<p><b>${i+1}. ${r.name}</b><br>${r.hints[2]}<br>解释要点：${r.question.explain}</p>`).join('')}</details><div class="modal-actions"><button data-action="motion">${state.reduced?'恢复设备动画':'减少动态效果'}</button><button data-action="reset-confirm">重新开始一轮</button><button class="primary" data-action="close">知道了</button></div>`);}
function assessmentData(){if(!state.assessment||typeof state.assessment!=='object')state.assessment={answers:{},submitted:false};if(!state.assessment.answers||typeof state.assessment.answers!=='object')state.assessment.answers={};return state.assessment;}
const transferOptions={transferDevice:['照明灯','电风扇','洗衣机','电饭锅','路灯'],transferFunction:['提供照明','促进空气流动','完成脱水','煮粥','提供夜间照明'],transferMethod:['按开关','打开电源并选择风速','开启电源并选择模式','按照明开关','观察设备结果后再调整'],transferEvidence:['观察房间是否变亮','观察气流是否让机关移动','观察设备是否执行所需模式','观察是否按时停止','观察街道是否变亮']};
function transferChoices(key,label){const a=assessmentData().answers;return `<fieldset class="transfer-group"><legend>${label}</legend><div class="assessment-options">${transferOptions[key].map(value=>`<button type="button" class="assessment-option ${a[key]===value?'selected':''}" data-action="transfer-answer" data-id="${key}" data-value="${esc(value)}" aria-pressed="${a[key]===value}">${esc(value)}</button>`).join('')}</div></fieldset>`;}
function assessmentPanel(){const a=assessmentData(),result=scoreAssessment(a.answers),challenge=state.challenge;return `<section class="assessment-card"><div class="eyebrow">FINAL CHECK · 探险任务单</div><h2>出口档案考核</h2><p class="assessment-intro">不用长篇打字：点击五个判断，再用选项拼出一句迁移表达。这里对应任务单里的“设备—功能—控制方法、街道设备、调整解释、设备发展和身边迁移”。</p>${finalAssessment.map((item,index)=>`<fieldset class="assessment-item"><legend><span>${index+1}</span>${esc(item.label)}</legend><p>${esc(item.prompt)}</p><div class="assessment-options">${item.options.map((option,i)=>`<button type="button" class="assessment-option ${a.answers[item.id]===i?'selected':''}" data-action="assessment-answer" data-id="${item.id}" data-value="${i}" aria-pressed="${a.answers[item.id]===i}">${String.fromCharCode(65+i)} · ${esc(option)}</button>`).join('')}</div></fieldset>`).join('')}<div class="transfer-builder"><div class="eyebrow">MY TRANSFER · 选项拼句</div>${transferChoices('transferDevice','我选择的设备')}${transferChoices('transferFunction','它要实现的功能')}${transferChoices('transferMethod','我会采用的控制方法')}${transferChoices('transferEvidence','我会观察的结果')}<p class="assessment-sentence" aria-live="polite">${result.transfer.sentence||'选择四项后，这里会生成你的迁移表达。'}</p></div><div class="project-evidence"><b>项目证据</b><span>${challenge?.selfTest?'✓ 已完成自创机关自测':'○ 尚未完成自创机关自测'}</span><span>${challenge?.peerPassed?'✓ 已有同伴验证':'○ 尚未有同伴验证'}</span><small>自创机关的理由、验证和修改会一并写入报告；不要求在这里重新打字。</small></div><button class="primary assessment-submit" data-action="assessment-submit" ${result.ready?'':'disabled'}>${a.submitted?'已提交 · 再次提交会更新记录':'提交终局考核'}</button>${a.submitted?`<div class="assessment-result ${result.complete?'success':''}" role="status"><b>${result.complete?'✓ 任务单考核完成':'已记录：'+result.score+' / '+result.max+' 项判断正确'}</b><span>${result.complete?'迁移表达也已生成，可以导出报告。':'回看线索簿或密室后，可以修改选项再提交。'}</span></div>`:''}</section>`;}
function finish(){return `<div class="final-wrap"><section class="finish-hero"><div class="eyebrow">THE GATE IS OPEN</div><h1>出口已开启，探索还在继续。</h1><p>你通过操作、观察和解释，点亮了五枚晶石。现在，把密室里的发现带回身边：设备怎样回应我们的控制？</p><div class="badge-row"><span class="pill">◈ 设备观察员</span><span class="pill">✧ 控制探索者</span><span class="pill">⌛ 科技发现者</span></div></section><div class="achievement-grid"><div class="achievement"><b>${state.attempts.filter(a=>a.ok).length}/18</b><span>操作任务通过</span></div><div class="achievement"><b>${state.passed.filter(Boolean).length}/6</b><span>解释取证通过</span></div><div class="achievement"><b>${minutes()}分钟</b><span>本页有效活动时间 · 不评分</span></div></div>${assessmentPanel()}<div class="finish-grid"><section><div class="eyebrow">MY EVIDENCE</div><h2>带走我的发现</h2><p>线索簿保留设备、控制方法、观察结果和终局考核，可直接导出给教师。</p><button class="primary" data-action="notebook">查看并导出线索簿 →</button></section><section><div class="eyebrow">CREATE A CHALLENGE</div><h2>换我来设计机关</h2><p>设计一张风力机关卡，先自己验证，再交换给同伴尝试，根据反馈修改。</p><button class="gold" data-action="creator">设计同伴挑战 →</button></section></div><div class="modal-actions"><button data-action="review">回看密室</button><button class="plain" data-action="reset-confirm">重新开始一轮</button></div></div>`;}
function operation(c,r,s){if(r===0||r===5&&s!==1)return s===2?`播放器${c.audio?'开':'关'}，音量${c.volume}格`:`照明${c.lamp?'开':'关'}；投影${c.projector?'开':'关'}；窗帘${c.curtain?'合':'开'}`;if(r===1||r===5)return `风扇${c.fan?'开':'关'}，${c.speed}挡，${c.timer?'定时'+c.timer+'分钟':'不定时'}`;if(r===2)return s<2?`洗衣机${c.washer?'开':'关'}，${c.wmode}`:`电饭锅${c.cooker?'开':'关'}，${c.cmode}`;if(r===3)return `${c.role}；车辆${c.vehicle?'开':'关'}；信号${c.signal}；路灯${c.street?'开':'关'}`;return s===0?`${c.key}；${c.oldOpen?'已转动开锁':'未开锁'}`:s===1?`模拟密码${c.code}；${c.smartOpen?'验证开锁':'未开锁'}`:c.evolution;}
async function run(){if(pending||busy||state.steps[state.room]>=3)return;const r=state.room,s=state.steps[r],c={...state.controls[r]},prediction=state.predictions[r];if(!prediction){feedback={ok:false,text:'请先选一个预测。可以选“还不确定”，再用试验比较。'};render();$('#prediction')?.focus();return;}busy=true;feedback={ok:false,text:'设备正在按当前设置运行，请观察画面与状态。'};render();await new Promise(resolve=>setTimeout(resolve,state.reduced?100:650));const result=check(r,s,c);const timed=result.ok&&((r===1&&s===2)||(r===5&&s===1));if(timed){feedback={ok:false,text:'时间快进：模拟第15分钟，风扇仍在运行……'};render();await new Promise(resolve=>setTimeout(resolve,state.reduced?100:850));state.controls[r].fan=false;result.text+='。模拟30分钟已到，风扇停止；这不是实际等待30分钟。';}
state.attempts.push({room:r,step:s,title:rooms[r].tasks[s].title,prediction,operation:operation(c,r,s),ok:result.ok,result:result.text,seconds:state.elapsed});state.attempts=state.attempts.slice(-500);busy=false;feedback=result;pending=result.ok;state.pending[r]=result.ok;if(result.ok)sound();save();render();}
const discoveryTexts=[
 ['灯的开关控制照明功能。留意开关动作与房间变化。','幕布负责显示投影；看清图案还与环境光有关。','同一个房间里的不同设备，为不同需要服务。'],
 ['挡位改变风速，定时改变运行到何时停止。','风扇吹动空气。这里用气流推动机关，是游戏模拟。','轻风未必“差”，强风未必“好”，要看任务需要。'],
 ['电源打开只表示设备启动，还要检查工作模式。','洗衣机可以快洗，也可以脱水；功能不同，模式不同。','电饭锅的煮饭、煮粥、保温是不同功能。'],
 ['驾驶员控制车辆，实现出行。','交通信号灯帮助有序通行；路灯提供照明。','有些为生活服务的设备并不在眼前，例如导航卫星。'],
 ['钥匙与锁孔匹配后，还需要转动钥匙来开锁。','智能门锁可以有多种开锁方式；本关只模拟密码。','多种形式的门锁可以并存，科技进步带来更多选择。'],
 ['线索簿保存着控制方法，可以迁移到新任务。','先预测，再操作，观察结果，再调整。','常见设备可以看作控制系统；它们按规则实现功能。']
];
function assessmentReport(){const a=assessmentData(),result=scoreAssessment(a.answers);return `<h2>终局任务单考核</h2><p>五项判断：${result.score}/${result.max}；${a.submitted?(result.complete?'已完成':'已提交，部分判断需要回看线索'):'尚未提交'}。</p>${finalAssessment.map(item=>`<p><b>${esc(item.label)}</b>：${a.answers[item.id]===undefined?'未选择':esc(item.options[a.answers[item.id]])}（${a.answers[item.id]===item.correct?'正确':'待调整'}）</p>`).join('')}<p><b>迁移表达：</b>${result.transfer.sentence?esc(result.transfer.sentence):'尚未拼出'}</p>`;}
function exportReport(){const body=`<h1>机关密室 · 学习证据报告</h1><p>小组代号：${esc(state.name||'未填写')}　已取证：${state.passed.filter(Boolean).length}/6　有效活动时间：${minutes()}分钟（不评分）</p>${assessmentReport()}<h2>设备—控制方法—观察结果</h2>${tableRecords()}<h2>解释尝试</h2>${state.answers.map(a=>`<p><b>${esc(rooms[a.room].name)}</b>：${esc(a.answer)}（${a.ok?'正确':'继续思考'}）</p>`).join('')}<h2>迁移表达（旧版开放记录）</h2><p style="white-space:pre-wrap">${esc(state.reflection||'未使用长文本输入')}</p><h2>自创机关与同伴验证</h2>${state.challenge?`<p>${esc(state.challenge.title)}；目标风速${state.challenge.speed}挡；定时${state.challenge.timer}分钟。</p><p>设计理由：${esc(state.challenge.reason)}</p><p>设计者验证：${state.challenge.selfTest?'通过':'未通过或未进行'}；同伴试验${state.challenge.peerAttempts||0}次；通过${state.challenge.peerPassed?'是':'否'}。</p><p>同伴建议：${esc(state.challenge.peerFeedback||'未填写')}</p><p>修改说明：${esc(state.challenge.revision||'未填写')}</p>${(state.challenge.history||[]).map(h=>`<p>此前版本：${esc(h.title)}，${h.speed}挡/${h.timer}分钟；同伴试验${h.peerAttempts||0}次，通过${h.peerPassed?'是':'否'}；建议：${esc(h.peerFeedback||'未填写')}</p>`).join('')}`:'<p>尚未设计。</p>'}<p>提示使用量：${state.hints.join(' / ')}（仅供观察，不据此扣分）。教学目标：设备控制方法、生活中的控制系统、控制系统的发展变化。</p><p>说明：以上为当前浏览器内的学习记录；选择题由游戏判定，终局考核中的迁移表达由选项拼成，开放回答不自动评分。</p>`;download(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>机关密室学习证据</title><style>body{max-width:1000px;margin:35px auto;padding:20px;font:15px/1.8 system-ui;color:#1b383a}h1,h2{color:#205d53}table{width:100%;border-collapse:collapse;font-size:13px}td,th{padding:10px;border:1px solid #a9bcb8;text-align:left}th{background:#eaf3ef}@media print{body{margin:0}}</style><body>${body}</body></html>`,'机关密室—学习证据报告.html','text/html;charset=utf-8');}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('报告已交给浏览器下载，请查看下载列表。');}
let partnerControls={fan:false,speed:0,timer:0};
function creator(){const c=state.challenge||{title:'轻风护送羽片',speed:1,timer:30,reason:'',peerFeedback:'',revision:''};openModal('机关设计台 · 让同伴验证你的想法',`<p>用风扇设计一个可完成的机关。为同伴写清任务，但由同伴决定怎样操作。</p><label for="challenge-title">机关名称 / 要完成的事</label><input id="challenge-title" maxlength="60" value="${esc(c.title)}"><label for="challenge-speed">需要的风速</label><select id="challenge-speed">${[1,2,3].map(n=>`<option ${c.speed===n?'selected':''}>${n}</option>`).join('')}</select><label for="challenge-timer">需要何时停止（分钟）</label><select id="challenge-timer">${[15,30,60].map(n=>`<option ${c.timer===n?'selected':''}>${n}</option>`).join('')}</select><label for="challenge-reason">为什么这样设置？</label><textarea id="challenge-reason" maxlength="300" placeholder="例如：羽片很轻，需要小风；我希望装置到时间后停止。">${esc(c.reason)}</textarea><label for="challenge-revision">收到建议后，我修改了什么？（首次可留空）</label><textarea id="challenge-revision" maxlength="300">${esc(c.revision||'')}</textarea><div class="modal-actions"><button class="primary" data-action="save-challenge">保存并自己试验</button></div>`);}
let peerMode=false;
function partnerPanel(){const c=state.challenge;openModal(peerMode?'同伴挑战 · 试着控制机关':'设计者试验 · 先验证你的机关',`<p><b>${esc(c.title)}</b></p><p>让风扇以 <b>${c.speed} 挡</b>运行，并在 <b>${c.timer} 分钟</b>后停止。请操作后检验。</p><div class="record-item"><button data-action="peer-power" aria-pressed="${partnerControls.fan}">电源：${partnerControls.fan?'已开':'已关'}</button><label for="peer-speed">风速 / 挡</label><select id="peer-speed">${[0,1,2,3].map(n=>`<option ${partnerControls.speed===n?'selected':''}>${n}</option>`).join('')}</select><label for="peer-timer">定时 / 分钟（0为不定时）</label><select id="peer-timer">${[0,15,30,60].map(n=>`<option ${partnerControls.timer===n?'selected':''}>${n}</option>`).join('')}</select><p id="peer-result" role="status">${partnerControls.fan?'风扇已启动，请检查风速与定时。':'风扇尚未启动。'}</p><button class="primary" data-action="peer-run">试运行并检验</button></div>${peerMode?`<label for="peer-feedback">同伴建议：任务是否清楚？怎样改进？</label><textarea id="peer-feedback" maxlength="300">${esc(c.peerFeedback||'')}</textarea>`:''}<div class="modal-actions"><button data-action="creator">返回设计台修改</button>${!peerMode&&c.selfTest?'<button class="gold" data-action="peer-start">交给同伴挑战</button>':''}<button data-action="export">导出包含机关卡的报告</button></div>`);}
let lastActivity=Date.now();
document.addEventListener('pointerdown',()=>lastActivity=Date.now(),{passive:true});
document.addEventListener('keydown',()=>lastActivity=Date.now());
document.addEventListener('input',e=>{const x=e.target;if(x.id==='team-name')state.name=x.value.slice(0,30);else if(x.id==='reflection')state.reflection=x.value.slice(0,800);else if(x.id==='peer-feedback'&&state.challenge)state.challenge.peerFeedback=x.value.slice(0,300);else return;save();});
document.addEventListener('change',e=>{const x=e.target;if(x.id==='prediction'){state.predictions[state.room]=x.value;save();}if(x.id==='peer-speed')partnerControls.speed=Number(x.value);if(x.id==='peer-timer')partnerControls.timer=Number(x.value);});
document.addEventListener('click',async e=>{
 const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,r=state.room,c=state.controls[r],s=state.steps[r];
 if(busy&& !['sound','motion','close'].includes(a))return;
 if(a==='close'){$('#modal').close();return;}
 if(a==='notebook'){noteBook();return;}
 if(a==='export'){exportReport();return;}
 if(a==='assessment-answer'){const data=assessmentData();data.answers[b.dataset.id]=Number(b.dataset.value);data.submitted=false;save();render();return;}
 if(a==='transfer-answer'){const data=assessmentData();data.answers[b.dataset.id]=b.dataset.value;data.submitted=false;save();render();return;}
 if(a==='assessment-submit'){const data=assessmentData(),result=scoreAssessment(data.answers);if(!result.ready){toast('请完成五个判断和四个迁移选项，再提交终局考核。');return;}data.submitted=true;save();render();return;}
 if(a==='start'){state.started=true;save();render();window.scrollTo(0,0);return;}
 if(a==='sound'){state.sound=!state.sound;save();render();if(state.sound)sound();return;}
 if(a==='motion'){state.reduced=!state.reduced;save();render();toast(state.reduced?'已减少动态效果，操作与线索仍然有效。':'已恢复设备动画。');return;}
 if(a==='room'){const n=Number(b.dataset.room);if(n>0&&!state.passed[n-1])return;state.room=n;pending=!!state.pending?.[n];feedback=pending?{ok:true,text:'这个任务已经通过，点击“记录发现，继续”。'}:null;save();render();return;}
 if(a==='run'){await run();return;}
 if(a==='next-step'&&pending){state.steps[r]=Math.min(3,s+1);pending=false;state.pending[r]=false;feedback=null;state.predictions[r]='';save();render();const title=$('.task-panel h2, .task-panel h3');if(title){title.tabIndex=-1;title.focus({preventScroll:true});title.scrollIntoView({block:'nearest',behavior:'auto'});}return;}
 if(a==='hint'){state.hints[r]=Math.min(3,state.hints[r]+1);save();render('hint');return;}
 if(a==='discover'){const n=Number(b.dataset.discovery),id=r+'-'+n;if(!state.discoveries.includes(id))state.discoveries.push(id);save();render();toast(discoveryTexts[r][n]);return;}
 if(a==='answer'&&s===3&&!state.passed[r]){const n=Number(b.dataset.answer),q=rooms[r].question,ok=n===q.correct;state.answers.push({room:r,answer:q.options[n],ok});feedback={ok,text:ok?q.explain:'再想一想你的操作经历。需要把设备、控制方法和实现的功能联系起来。'};if(ok){state.passed[r]=true;sound();}save();render(ok?'next-room':b.dataset.focus);return;}
 if(a==='next-room'&&state.passed[r]){if(r===5)state.finished=true;else state.room=r+1;feedback=null;pending=!!state.pending?.[state.room];save();render();window.scrollTo(0,0);return;}
 if(a==='review'){state.finished=false;state.room=0;feedback=null;pending=false;save();render();return;}
 if(a==='reset-confirm'){openModal('重新开始一轮？','<p>这会清除当前浏览器中的本轮进度、线索簿和机关卡。可以先导出报告，再重新开始。</p><div class="modal-actions"><button data-action="export">先导出报告</button><button class="gold" data-action="reset">确认重新开始</button><button data-action="close">保留当前进度</button></div>');return;}
 if(a==='reset'){state=fresh();pending=false;feedback=null;save();$('#modal').close();render();return;}
 if(a==='creator'){creator();return;}
 if(a==='save-challenge'){
  const title=$('#challenge-title').value.trim(),reason=$('#challenge-reason').value.trim();if(!title||!reason){toast('请写清机关任务和设计理由，再进行试验。');return;}
  const prev=state.challenge,speed=Number($('#challenge-speed').value),timer=Number($('#challenge-timer').value);const changed=!!prev&&(prev.title!==title||prev.speed!==speed||prev.timer!==timer);const history=prev?.history||[];if(changed)history.push({title:prev.title,speed:prev.speed,timer:prev.timer,selfTest:prev.selfTest,peerAttempts:prev.peerAttempts,peerPassed:prev.peerPassed,peerFeedback:prev.peerFeedback});state.challenge={title,speed,timer,reason,revision:$('#challenge-revision').value.trim(),peerFeedback:prev?.peerFeedback||'',selfTest:changed?false:prev?.selfTest||false,peerAttempts:changed?0:prev?.peerAttempts||0,peerPassed:changed?false:prev?.peerPassed||false,history};save();partnerControls={fan:false,speed:0,timer:0};peerMode=false;partnerPanel();return;
 }
 if(a==='peer-start'&&state.challenge?.selfTest){peerMode=true;partnerControls={fan:false,speed:0,timer:0};partnerPanel();return;}
 if(a==='peer-power'){partnerControls.fan=!partnerControls.fan;partnerPanel();return;}
 if(a==='peer-run'&&state.challenge){const t=state.challenge,ok=partnerControls.fan&&partnerControls.speed===t.speed&&partnerControls.timer===t.timer;if(peerMode){t.peerAttempts++;t.peerPassed=ok||t.peerPassed;}else t.selfTest=ok;if(ok)sound();save();partnerPanel();$('#peer-result').textContent=ok?'✓ 控制方案通过：风扇以指定挡位运行，并设置了对应停止时间。现在可以交流理由与改进建议。':'还没有满足任务。检查电源、风速与定时，再调整一个设置试试看。';return;}
 if(pending||s>=3)return;
 if(a==='toggle'){c[b.dataset.key]=!c[b.dataset.key];feedback=null;save();render(b.dataset.focus);return;}
 if(a==='set'){const k=b.dataset.key;c[k]=b.dataset.number==='true'?Number(b.dataset.value):b.dataset.value;if(k==='key')c.oldOpen=false;feedback=null;save();render(b.dataset.focus);return;}
 if(a==='old-lock'){c.oldOpen=c.key==='齿形钥匙';feedback={ok:c.oldOpen,text:c.oldOpen?'匹配的钥匙带动锁芯，机械锁打开了。现在可以预测并试运行记录。':'钥匙与锁孔不匹配，锁没有打开。查看锁孔提示。'};}
 if(a==='digit'){if(c.code.length>=3){toast('已经输入3位。需要改动时按“清除”。');return;}c.code+=b.dataset.digit;c.smartOpen=false;feedback=null;}
 if(a==='clear-code'){c.code='';c.smartOpen=false;feedback=null;}
 if(a==='smart-lock'){c.smartOpen=c.code==='246';feedback={ok:c.smartOpen,text:c.smartOpen?'密码验证通过，智能锁打开了。现在可以预测并试运行记录。':'密码没有通过验证，门锁保持关闭。按清除后重新输入。'};}
 save();render(b.dataset.focus);
});
setInterval(()=>{if(state.started&&!state.finished&&!document.hidden&&Date.now()-lastActivity<90000){state.elapsed++;if(state.elapsed%15===0)save();}},1000);
window.addEventListener('pagehide',save);
render();
})();
